<a href="https://colab.research.google.com/github/farahenany/Dissertation/blob/main/Discriminant_Analysis_for_UK_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn import datasets
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [ ]:
pd.options.display.max_columns = None

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
customer_base = pd.read_csv("drive/MyDrive/Dissertation/Dissertation/customer_retail_bank/Proposition.csv")
customer_base

Numcust       TRB  Primary_cust  Digital_cust  CA_holders  \
0      0.070379 -0.243790      0.340697      0.252573   -0.270957   
1      0.177381 -0.199371      0.487501      0.381397   -0.270957   
2      0.070379 -0.243790      0.340697      0.252573   -0.270957   
3      0.070379 -0.243790      0.340697      0.252573   -0.270957   
4      0.070379 -0.243790      0.340697      0.252573   -0.270957   
...         ...       ...           ...           ...         ...   
55291 -0.143626 -0.322757     -0.246518     -0.262722   -0.058875   
55292 -0.304130 -0.396788     -0.246518     -0.262722   -0.217937   
55293  0.070379 -0.224048     -0.246518     -0.262722    0.153207   
55294 -0.143626 -0.322757     -0.246518     -0.262722   -0.058875   
55295 -0.036624 -0.273403     -0.246518     -0.262722    0.047166   

       Card_holders  Ins_holders  Inv_holders  Mort_holders  Primary  \
0         -0.235752     2.060290    -0.321304     -0.251197        2   
1         -0.235752     2.701543    -0.321304     -0.251197        2   
2         -0.235752     2.060290    -0.321304     -0.251197        2   
3         -0.235752     2.060290    -0.321304      0.298711        2   
4         -0.235752     2.060290    -0.321304      0.298711        2   
...             ...          ...          ...           ...      ...   
55291     -0.007279    -0.504723     0.217131     -0.251197        1   
55292     -0.178633    -0.504723    -0.186695     -0.251197        1   
55293      0.221195    -0.504723     0.755567      0.298711        1   
55294     -0.007279    -0.504723     0.217131      0.023757        1   
55295      0.106958    -0.504723     0.486349      0.161234        1   

       International  CA  Card  Insurance  Investment  Mortgage  Digital  \
0                  1   1     1          2           1         1        2   
1                  1   1     1          2           1         1        2   
2                  1   1     1          2           1         1        2   
3                  1   1     1          2           1         2        2   
4                  1   1     1          2           1         2        2   
...              ...  ..   ...        ...         ...       ...      ...   
55291              2   2     2          1           2         1        1   
55292              2   2     2          1           2         1        1   
55293              2   2     2          1           2         2        1   
55294              2   2     2          1           2         2        1   
55295              2   2     2          1           2         2        1   

      Proposition  Tenure Age  NPS  Revenue  
0       3. Bronze       2   2    3    12000  
1       3. Bronze       2   2    2    15000  
2       3. Bronze       2   2    1    12000  
3       3. Bronze       2   2    3    12000  
4       3. Bronze       2   2    2    12000  
...           ...     ...  ..  ...      ...  
55291     1. Gold       3   1    2    40000  
55292     1. Gold       3   1    1    10000  
55293     1. Gold       3   1    3    80000  
55294     1. Gold       3   1    2    40000  
55295     1. Gold       3   1    1    60000  

[55296 rows x 22 columns]

In [ ]:
customer_base

Numcust       TRB  Primary_cust  Digital_cust  CA_holders  \
0      0.070379 -0.243790      0.340697      0.252573   -0.270957   
1      0.177381 -0.199371      0.487501      0.381397   -0.270957   
2      0.070379 -0.243790      0.340697      0.252573   -0.270957   
3      0.070379 -0.243790      0.340697      0.252573   -0.270957   
4      0.070379 -0.243790      0.340697      0.252573   -0.270957   
...         ...       ...           ...           ...         ...   
55291 -0.143626 -0.322757     -0.246518     -0.262722   -0.058875   
55292 -0.304130 -0.396788     -0.246518     -0.262722   -0.217937   
55293  0.070379 -0.224048     -0.246518     -0.262722    0.153207   
55294 -0.143626 -0.322757     -0.246518     -0.262722   -0.058875   
55295 -0.036624 -0.273403     -0.246518     -0.262722    0.047166   

       Card_holders  Ins_holders  Inv_holders  Mort_holders  Primary  \
0         -0.235752     2.060290    -0.321304     -0.251197        2   
1         -0.235752     2.701543    -0.321304     -0.251197        2   
2         -0.235752     2.060290    -0.321304     -0.251197        2   
3         -0.235752     2.060290    -0.321304      0.298711        2   
4         -0.235752     2.060290    -0.321304      0.298711        2   
...             ...          ...          ...           ...      ...   
55291     -0.007279    -0.504723     0.217131     -0.251197        1   
55292     -0.178633    -0.504723    -0.186695     -0.251197        1   
55293      0.221195    -0.504723     0.755567      0.298711        1   
55294     -0.007279    -0.504723     0.217131      0.023757        1   
55295      0.106958    -0.504723     0.486349      0.161234        1   

       International  CA  Card  Insurance  Investment  Mortgage  Digital  \
0                  1   1     1          2           1         1        2   
1                  1   1     1          2           1         1        2   
2                  1   1     1          2           1         1        2   
3                  1   1     1          2           1         2        2   
4                  1   1     1          2           1         2        2   
...              ...  ..   ...        ...         ...       ...      ...   
55291              2   2     2          1           2         1        1   
55292              2   2     2          1           2         1        1   
55293              2   2     2          1           2         2        1   
55294              2   2     2          1           2         2        1   
55295              2   2     2          1           2         2        1   

      Proposition  Tenure Age  NPS  Revenue  
0       3. Bronze       2   2    3    12000  
1       3. Bronze       2   2    2    15000  
2       3. Bronze       2   2    1    12000  
3       3. Bronze       2   2    3    12000  
4       3. Bronze       2   2    2    12000  
...           ...     ...  ..  ...      ...  
55291     1. Gold       3   1    2    40000  
55292     1. Gold       3   1    1    10000  
55293     1. Gold       3   1    3    80000  
55294     1. Gold       3   1    2    40000  
55295     1. Gold       3   1    1    60000  

[55296 rows x 22 columns]

In [ ]:
customer_base['Age'] = customer_base['Age'].str.replace('+', '')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


In [ ]:
customer_base['Age'] = customer_base['Age'].astype(float, errors = 'raise')

In [ ]:
customer_base.dtypes

Numcust          float64
TRB              float64
Primary_cust     float64
Digital_cust     float64
CA_holders       float64
Card_holders     float64
Ins_holders      float64
Inv_holders      float64
Mort_holders     float64
Primary            int64
International      int64
CA                 int64
Card               int64
Insurance          int64
Investment         int64
Mortgage           int64
Digital            int64
Proposition       object
Tenure             int64
Age              float64
NPS                int64
Revenue            int64
dtype: object

In [ ]:
customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'2. Silver',"Silver" )
customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'1. Gold',"Gold" )
customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'3. Bronze',"Bronze" )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
X = customer_base[['Primary', 'Tenure', 'Age', 'International','CA', 'Card', 'Insurance', 'Investment', 'Mortgage',
        'NPS', 'Digital', 'TRB', 'Revenue'	,'Primary_cust', 'Digital_cust', 'CA_holders', 'Card_holders', 'Ins_holders', 
        'Inv_holders', 'Mort_holders']]
y = customer_base['Proposition']


In [ ]:
#Fit the LDA model
model = LinearDiscriminantAnalysis()
model.fit(X, y)

LinearDiscriminantAnalysis()

In [ ]:
#Define method to evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

#evaluate model
scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
print(np.mean(scores))  
# this is the model performance accuracy

0.7995937579823237


This model performs with an accuracy of 80 if the bank is presente witha new customer , inputing these givens the bank can identify to which proposition will the customer belong to.

### getting model attributes


In [ ]:
model.coef_

array([[ 2.46289389e-01, -1.35927597e-03, -5.89929630e-04,
        -9.50269506e-05,  4.09760148e-01,  5.33863462e-02,
        -9.58909192e-01, -1.71870599e-01,  5.42394531e-02,
        -1.18996464e-03,  5.68800056e-01, -5.22524697e-01,
        -4.02794424e-05,  1.08315745e+00, -5.17255349e-02,
         7.45448555e-01, -2.92140819e-01,  1.21388917e-01,
         9.94638027e-02,  7.44643342e-02],
       [ 2.72241339e-01,  3.06704985e-03,  2.08137106e-04,
         1.48064076e-04, -1.03544826e-01, -2.31991826e-01,
         8.34724393e-01,  3.49692518e-01,  9.84414431e-03,
         4.18640005e-04, -7.91784072e-01, -6.01432192e-01,
         7.09307123e-05, -1.49888035e+00,  8.32170635e-02,
        -1.18896731e+00,  5.96384578e-01, -1.29066180e-01,
        -2.20850828e-01, -3.18432007e-02],
       [-5.18530727e-01, -1.70777389e-03,  3.81792524e-04,
        -5.30371250e-05, -3.06215322e-01,  1.78605480e-01,
         1.24184799e-01, -1.77821920e-01, -6.40835974e-02,
         7.71324638e-04,  2.2

In [ ]:
model.intercept_

array([-0.69359273, -5.57707183,  0.25783146])

In [ ]:
model.explained_variance_ratio_

array([0.87212289, 0.12787711])

In [ ]:
model.means_

array([[ 1.50000000e+00,  2.50000000e+00,  3.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         2.00000000e+00,  1.50000000e+00, -2.06830604e-01,
         1.78515625e+04,  4.08117903e-01,  3.77308124e-01,
         4.90810171e-01,  5.84666611e-01,  6.18757211e-01,
         1.41618281e-01,  3.62534369e-01],
       [ 1.50000000e+00,  2.50000000e+00,  3.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         2.00000000e+00,  1.50000000e+00,  4.98074220e-01,
         8.49538845e+04,  7.83431159e-02,  7.52724625e-02,
        -6.36961620e-03, -1.07149559e-03,  6.19766127e-01,
         2.44042793e-01,  4.31193616e-02],
       [ 1.50000000e+00,  2.50000000e+00,  3.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         1.50000000e+00,  1.50000000e+00,  1.50000000e+00,
         2.00000000e+00,  1.5

In [ ]:
model.priors_

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
model.n_features_in_

20

In [ ]:
model.feature_names_in_

array(['Primary', 'Tenure', 'Age', 'International', 'CA', 'Card',
       'Insurance', 'Investment', 'Mortgage', 'NPS', 'Digital', 'TRB',
       'Revenue', 'Primary_cust', 'Digital_cust', 'CA_holders',
       'Card_holders', 'Ins_holders', 'Inv_holders', 'Mort_holders'],
      dtype=object)

In [ ]:
new = [1,1,2,2,2,2,2,1,1,2,1,30,40,1,1,2,2,2,1,1]

#predict which class the new observation belongs to
model.predict([new])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearDiscriminantAnalysis was fitted with feature names
  "X does not have valid feature names, but"


array(['Silver'], dtype='<U6')

In [ ]:
df['target'].value_counts()


0.0    50
1.0    50
2.0    50
Name: target, dtype: int64

In [ ]:
proposition_df= customer_base['Proposition']

In [ ]:

customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'2. Silver',"Silver" )
customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'1. Gold',"Gold" )
customer_base['Proposition'] = customer_base['Proposition'].str.replace(r'3. Bronze',"Bronze" )

array([[ 2.        ,  2.        ,  2.        , ...,  2.06028969,
        -0.32130399, -0.25119742],
       [ 2.        ,  2.        ,  2.        , ...,  2.7015429 ,
        -0.32130399, -0.25119742],
       [ 2.        ,  2.        ,  2.        , ...,  2.06028969,
        -0.32130399, -0.25119742],
       ...,
       [ 1.        ,  3.        ,  1.        , ..., -0.50472314,
         0.7555665 ,  0.29871104],
       [ 1.        ,  3.        ,  1.        , ..., -0.50472314,
         0.21713125,  0.02375681],
       [ 1.        ,  3.        ,  1.        , ..., -0.50472314,
         0.48634888,  0.16123392]])

### SVM

In [ ]:
from sklearn import svm
from sklearn.svm import SVC


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=109) # 70% training and 30% test

In [ ]:
#Import svm model
from sklearn.svm import SVC
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)